name: Deploy

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install npm-check-updates   
        run: npm install -g npm-check-updates
      - name: functions npm-check-updates
        run: |
          cd functions
          ncu
          ncu -u
      - name: local npm-check-updates
        run: |
          cd local
          ncu
          ncu -u
      - name: func install
        run: |
          cd functions/
          npm install
      - name: build
        run: |
          cd local/
          npm install
          npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
